/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CueColumn: typeof import('./src/components/mainContent/areas/CueColumn.vue')['default']
    HeaderBlock: typeof import('./src/components/header/HeaderBlock.vue')['default']
    NoteBlock: typeof import('./src/components/mainContent/NoteBlock.vue')['default']
    NoteColumn: typeof import('./src/components/mainContent/areas/NoteColumn.vue')['default']
    NoteTitle: typeof import('./src/components/mainContent/areas/NoteTitle.vue')['default']
    PagesList: typeof import('./src/components/sidebar/PagesList.vue')['default']
    SidebarBlock: typeof import('./src/components/sidebar/SidebarBlock.vue')['default']
    SummaryRow: typeof import('./src/components/mainContent/areas/SummaryRow.vue')['default']
  }
}
